
version: '2'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - learn-odoo
    restart: unless-stopped

  odoo:
    image: odoo:14.0
    command: -- --dev=reload
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8069:8069"
      - "8071:8071"
    volumes:
      # - ./etc:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - learn-odoo
    tty: true
    restart: unless-stopped

networks:
  learn-odoo:
    driver: bridge
 
